### ISSUE TITLE
Zork I [beta] - Wrong response to "destroy thief with sword"

### ISSUE THREAD

**Issue by eriktorbjorn** [the-infocom-files/zork1#3]
This is a bug that also happens in the released version of Zork I. Grab your sword, wait for the thief to appear, and...

```
>DESTROY THIEF WITH SWORD
Trying to attack a thief with your bare hands is suicidal.
```

I think the problem is in ```V-MUNG```, which looks like this:

```
<ROUTINE V-MUNG ()
	 <COND (<FSET? ,PRSO ,ACTORBIT>
		<PERFORM ,V?ATTACK ,PRSO>
		<RTRUE>)
	       (T
		<TELL "Nice try." CR>)>>
```

It should probably be ```<PERFORM ,V?ATTACK ,PRSO ,PRSI>``` instead.

**Comment by AlexProudfoot** [comment]
I can't conveniently reproduce the problem without a transcript but the code you have highlighted is definitely wrong. You'll need to let me know if this cures the problem before I can close the issue.

**Comment by eriktorbjorn** [comment]
Not sure what you mean by a transcript, but I hope this is useful.

What I did to reproduce it was to just enter the cellar and wait for the thief to appear. He will show up eventually (though you may have to wait for a while), since he moves between rooms simply by taking his current location and then look for the next sibling in ```ROOMS``` that doesn't have ```SACREDBIT```, if I read the code correctly.

If you want to seek him out, you have to kill the troll which adds some uncertainty right there. From the Troll Room, you can get to his lair either through the maze or through the secret entrance.

From the Troll Room through the maze:

```
W. S. E. U. SW. E. S. SE. ODYSSEUS. UP
```

From the Troll Room through the secret entrance. You'll need the rope from the attic.

```
E. E. SE. E. TIE ROPE TO RAILING. D. S. TREASURE
```

**Comment by eriktorbjorn** [comment]
By the way, whenever I suggest that a particular piece of code is wrong I've almost certainly tried changing it and given it a quick test. Of course, that doesn't always mean it's the _correct_ fix. :-)

**Comment by AlexProudfoot** [comment]
OK, thanks for that. I tried the waiting in the cellar option.

The previous behaviour was this.
~~~~
>wait
Time passes...
Someone carrying a large bag is casually leaning against one of the walls here.
He does not speak, but it is clear from his aspect that the bag will be taken
only over his dead body.
Your sword has begun to glow very brightly.

>destroy thief with sword
Trying to attack a thief with your bare hands is suicidal.
The thief just left, still carrying his large bag. You may not have noticed
that he robbed you blind first.

>
~~~~
It now works like this.
~~~~
>wait
Time passes...
Someone carrying a large bag is casually leaning against one of the walls here.
He does not speak, but it is clear from his aspect that the bag will be taken
only over his dead body.
Your sword has begun to glow very brightly.

>destroy thief with sword
A good slash, but it misses the thief by a mile.
The thief just left, still carrying his large bag. You may not have noticed
that he robbed you blind first.

>
~~~~

**Comment by AlexProudfoot** [comment]
See https://github.com/the-infocom-files/zork-substrate/commit/304a852fa0bea4940de989263d73048e304f28c7
