### ISSUE TITLE
Zork I [gamma?] - TRAP-DOOR not really a local global object

### ISSUE THREAD

**Issue by eriktorbjorn** [the-infocom-files/zork1#4]
This isn't even a bug, since it works, but...

```TRAP-DOOR``` is a local-global object, in the sense that it appears as a ```GLOBAL``` in ```CELLAR```. On the other hand, it's not since its location is ```LIVING-ROOM```, not ```LOCAL-GLOBALS```.

According to the ZIL manual, "Such objects are called local-globals and are "stored" in another one of those special objects, called LOCAL-GLOBALS.". But that's not actually the case because ```GLOBAL-CHECK``` doesn't actually test where the objects in the ```GLOBAL``` property are.

This probably isn't much of a problem in Zork I, but in Zork II it actually leads to a bug where the menhir is visible in the Menhir Room and the Kennel, even if the demon has removed it from ```LOCAL-GLOBALS```.

So stylistically, ```TRAP-DOOR``` should probably be in ```LOCAL-GLOBALS```, and then added to the ```GLOBAL``` property of ```LIVING-ROOM```. My only worry was that this would perhaps make the trap door visible even before the rug was moved, but a quick test indicates that this is not the case. Probably because it's invisible until the rug has been moved.

**Comment by AlexProudfoot** [comment]
Making the changes as described changes the disambiguation behaviour.

It was ...
~~~~
>open
What do you want to open?
~~~~
but now it is ...
~~~~
>open
(wooden door)
The door cannot be opened.
~~~~

**Comment by AlexProudfoot** [comment]
Putting WOODEN-DOOR into LOCAL-GLOBALS (where it belongs also) and making it global in LIVING-ROOM fixes the disambiguation behaviour.

**Comment by AlexProudfoot** [comment]
I think TRAP-DOOR and WOODEN-DOOR now belong in globals.zil in the zork-substrate repository.

**Comment by eriktorbjorn** [comment]
When you say WOODEN-DOOR belongs in LOCAL-GLOBALS, do you mean it should be visible from both LIVING-ROOM and STRANGE-PASSAGE? (Though in that case, should the gothic lettering be visible from both sides? It's only mentioned in the Living Room.)

**Comment by eriktorbjorn** [comment]
Hmm... Since the TRAP-DOOR and WOODEN-DOOR objects are only present in Zork I, I don't see why they should be in zork-substrate.

**Comment by AlexProudfoot** [comment]
1. WOODEN-DOOR is treated as a door in LIVING-ROOM only. I think this means that although (as I understand it) doors belong in LOCAL-GLOBALS, WOODEN-DOOR doesn't need to be global in STRANGE-PASSAGE.
2. You are right. Sorry for the brainfart. I got confused between global in ZIL and global across the 3 games.  :)

**Comment by eriktorbjorn** [comment]
I think it depends on the door, really. A quick look through Zork I, II and III shows most doors as being in LOCAL-GLOBALS. The exceptions I found were:

- [Zork I] TRAP-DOOR, which is (was) in LIVING-ROOM, but is still somehow a local global object.
- [Zork I] FRONT-DOOR, which is in WEST-OF-HOUSE. You don't ever see the other side, I think.
- [Zork I] BARROW-DOOR, which is in STONE-BARROW. You don't ever interact with the other side, because the game ends there.
- [Zork I] WOODEN-DOOR, which is (was) in LIVING-ROOM. You see the other side in STRANGE-PASSAGE, but I don't think you can interact with it. And the gothic lettering is probably just on one side. So in this case, perhaps keep it in LIVING-ROOM and add a pseudo object to STRANGE-PASSAGE? (Though you say that causes a disambiguation regression.) By the time you get to STRANGE-PASSAGE, there's always a hole in the door so you have no reason to try and open it.
- [Zork I] DOOR-PSEUDO. A pseudo object used in STUDIO.
- [Zork II] RIDDLE-DOOR, which is in RIDDLE-ROOM. I guess you never see the other side of it, even though it _should_ be visible.

**Comment by AlexProudfoot** [comment]
Thanks for that. Maybe I should check the effect of putting your examples in LOCAL-GLOBALS. If there are no further issues I could create issues to make it official.

**Comment by eriktorbjorn** [comment]
Well, TRAP-DOOR has already been changed, which I think is good since it didn't follow the rules set forth in the ZIL manual. The parser doesn't enforce the rule that a local global object has to be in LOCAL-GLOBALS, but at least for the Zork games perhaps it should? There is the bug in Zork II where the menhir - a local global object - is still accessible from the Menhir Room and Kennel, even if it's been moved out of LOCAL-GLOBALS. See https://github.com/the-infocom-files/zork2/issues/6

RIDDLE-DOOR should perhaps be a local global, but it's not mentioned in the PEARL-ROOM so maybe the door opened into a corridor and is now out of sight? If so, having it only in RIDDLE-ROOM should be fine I think.

FRONT-DOOR is a door you can only see one side of, so I see no reason for it to be a local global. (Both FRONT-DOOR and WOODEN-DOOR use the same action routine, but that's just code reuse. They can't be the same door.)

You don't ever interact with the other side of BARROW-DOOR, because the game ends at that point.

DOOR-PSEUDO isn't a real object, and you can only see it from STUDIO.

So WOODEN-DOOR is the only one _I_ think can sensibly be a local global object, because it _is_ mentioned in STRANGE-PASSAGE, which is why I asked if you meant to make it visible from there as well. But if so, the gothic lettering has to be fixed to only be visible from one side, perhaps by using an action routine for it instead of READBIT and TEXT. (I think it's ok that NAILS-PSEUDO is only in LIVING-ROOM. The door was probably nailed shut from that side.)

**Comment by AlexProudfoot** [comment]
Hey, maybe we need a wiki for issues like this. I was trying to suggest that, as a design convention, backdrop doors (i.e. objects with DOORBIT and NDESCBIT set) should be put in LOCAL-GLOBALS whether or not they are two-sided. What do you think?

**Comment by eriktorbjorn** [comment]
A wiki? Perhaps.

I guess I just don't see much point of putting an object in LOCAL-GLOBALS unless it's going to be visible from multiple locations. Mind you, I'm a rank amateur at ZIL. I'm just enjoying myself, going through at least the easy parts of the code, one routine at a time, and looking for bugs.

I'm estimating that at this rate it will take me several years to go through all of the games, so I _do_ hope you manage to attract more testers than just me. ;-)

**Comment by AlexProudfoot** [comment]
Also, in a sense, FRONT-DOOR and WOODEN-DOOR are not doors at all since they are never opened or used as DEXITs.

**Comment by AlexProudfoot** [comment]
Hey, however long it takes, I appreciate your help.  :)

**Comment by AlexProudfoot** [comment]
Maybe only two-sided doors should have DOORBIT set and be used as DEXITS? I’ll need to try some of these ideas out later.
