### ISSUE TITLE
Zork I [beta] - "play me" kills the player (may be deliberate)

### ISSUE THREAD

**Issue by eriktorbjorn** [the-infocom-files/zork1#5]
This happens if you "play me", implemented in ```V-PLAY```:

```
>PLAY ME
You become so engrossed in the role of the you that you kill yourself, just as
he might have done!


   ****  You have died  ****
```

Which _may_ be intentional (see below), but it's strangely worded and has an extra blank line compared to most other deaths.

For comparison, here's what the other versions I've tried says:

Mainframe Zork, Jeff Claar's C++ port:

```
>PLAY ME
You are so engrossed in the role of the cretin that
you kill yourself, just as he would have done!

As you take your last breath, you feel relieved of your burdens. The
feeling passes as you find yourself before the gates of Hell, where
the spirits jeer at you and deny you entry.  Your senses are
disturbed.  The objects in the dungeon appear indistinct, bleached of
color, even unreal.
```

Release 2, 5, 15, 20, 23, 25, 26, 28, 30:

```
>PLAY ME
I don't know the word 'play'.
```

Release 75, 76, 88:

```
>PLAY ME
That's silly!
```

Release 52 (Solid Gold):

```
>PLAY ME
You become so engrossed in the role of the you that you kill yourself, just as
he might have done!
 has no effect.

    ****  You have died  ****
```

So the only released version that has this particular death is the Solid Gold version, where it's slightly buggy.

So is it intentional? Well... The original MDL source code looks like this:

```zil
<DEFINE PLAY ()
    <COND (<==? <PRSO> <FIND-OBJ "STRAD">>
           <COND (<TRNN <PRSI> ,WEAPONBIT>
                  <TELL "Very good. The violin is now worthless.">
                  <OTVAL <PRSO> 0>)
                 (<TELL "An amazingly offensive noise issues from the violin.">)>)
          (<TRNN <PRSO> ,VILLAIN>
           <JIGS-UP 
"You are so engrossed in the role of the " 1 <ODESC2 <PRSO>> "that
you kill yourself, just as he would have done!">)>>
```

Which seems to imply that you should only be killed if you play a ```VILLAIN``` ("object is a bad guy"). But for some reason, the ```CRETIN``` object apparently has that bit:

```zil
<GOBJECT <>
         ["#####" "ME" "CRETI" "MYSEL" "SELF"]
         []
         "cretin"
         <+ ,OVISON ,VILLAIN>
         CRETIN
         ()
         (OGLOBAL 0
          OACTOR ,PLAYER)>
```

In Zork I, it just checks for ```ACTORBIT```. So who knows? At the very least, the extra line break should be removed. (And of course, the message in the Solid Gold version should be fixed, but that's a different project. I haven't even tried to figure that one out yet.)

**Comment by AlexProudfoot** [comment]
OK. This bug first appears in original release 119. It didn’t exist in original release 88 which was the last commercial release.

**Comment by AlexProudfoot** [comment]
The initial text comes from here.
```zil
<ROUTINE V-PLAY ()
    <COND (<FSET? ,PRSO ,ACTORBIT>
	   <TELL
"You become so engrossed in the role of the " D ,PRSO " that
you kill yourself, just as he might have done!" CR>
	   <JIGS-UP "">)
	  (ELSE <TELL "That's silly!" CR>)>>
```

**Comment by AlexProudfoot** [comment]
V-PLAY is in verbs.zil in zork-substrate.

**Comment by AlexProudfoot** [comment]
The extra text doesn't appear in the ZILF versions.

**Comment by AlexProudfoot** [comment]
To get "the cretin" instead of "the you", we could change the DESC property of object ME in globals.zil in zork-substrate.

**Comment by eriktorbjorn** [comment]
The Solid Gold version of Zork I doesn't use zork-substrate, does it? (I doubt the parser would work, since regular Zork I is ZIP while Solid Gold Zork I is XZIP.)

Anyway, this is what the compiled ```V-PLAY``` looks like in the official release:

```zil
Routine R0172, 0 locals
    Action routine for:
        "play OBJ"

       TEST_ATTR       G48,#2e [FALSE] L0001
       PRINT           "You become so engrossed in the role of the "
       PRINT_OBJ       G48
       PRINT           " that you kill yourself, just as he might have done!"
       NEW_LINE        
       CALL_2S         R0439 (S008) -> -(SP)
       RET_POPPED      
L0001: PRINT_RET       "That's silly!"
```

Which is almost identical to the one compiled by ZILF, except the ```S008``` string appears to be " has no effect.":

```zil
S008: " has no effect."
```

Which seems like a very bizarre programming error, indeed. In the ZILF-compiled version it uses an empty string instead, which would explain why there's no extra text.

**Comment by AlexProudfoot** [comment]
So R0439 is JIGS-UP I think. The source code calls JIGS-UP with an empty string parameter. I don’t know why the other text is referenced in the original releases. It comes from a table called HO-HUM which is only referenced by a routine called HACK-HACK. Yes, the solid-gold version has it’s own verbs.zil which seems to have the same problem in the original release. It also has it’s own globals.zil.

**Comment by AlexProudfoot** [comment]
I tried playing Zork on Confusion.

```
Welcome to 'Confusion', a MDL interpreter.
Copyright 2009 Matthew T. Russotto
This program comes with ABSOLUTELY NO WARRANTY; for details type <WARRANTY>.
This is free software, and you are welcome to distribute under certain conditions; type <COPYING> for details

This Zork created February 23, 2017.
West of House
This is an open field west of a white house, with a boarded front door.
There is a small mailbox here.
A rubber mat saying 'Welcome to Zork!' lies by the door.
> play me

 *ERROR*
 "TOO-MANY-ARGUMENTS-SUPPLIED"
LISTENING-AT-LEVEL 2 PROCESS 1
Atom REP has neither LVAL nor GVAL

```
Hmmm. I think the behaviour of the C++ port is the most sensible. Let's try for that. This will need the alterations in zork-substrate and zork1-invclues already discussed.

**Comment by eriktorbjorn** [comment]
Why zork-substrate, when the Solid Gold version doesn't use zork-substrate? (The original Zork I releases either don't understand the word "play", or call you silly for trying.)

**Comment by AlexProudfoot** [comment]
r119 behaves like the solid gold version as regards “play”

**Comment by AlexProudfoot** [comment]
This code is based on r119.

**Comment by AlexProudfoot** [comment]
![EA1A5B05-2588-4FE1-A4AB-AAFE71AA0292](https://user-images.githubusercontent.com/49520257/103466188-a82e9880-4d3a-11eb-8eb2-607d2aded52d.png)

**Comment by eriktorbjorn** [comment]
Ah, I forgot that. It's been a while since I tested Zork I. :-)

**Comment by AlexProudfoot** [comment]
No worries mate. It’s been a long time since I looked at any of this. Keep questioning. I’m grateful that someone else is interested enough to spend their time.  :)

**Comment by heasm66** [comment]
Just to clear up what is probably intented in the original MDL version.

There is an error on the line that calls JIGS-UP in the PLAY-routine. The line should be:

`	   <JIGS-UP <STRING
"You are so engrossed in the role of the " <ODESC2 <PRSO>> " that
you kill yourself, just as he would have done!">>)>>`

Whit this change the MDL version prints:

```
This Zork created January 5, 2021.
West of House
This is an open field west of a white house, with a boarded front door.
There is a small mailbox here.
A rubber mat saying 'Welcome to Zork!' lies by the door.

> play me
You are so engrossed in the role of the cretin that
you kill yourself, just as he would have done!

As you take your last breath, you feel relieved of your burdens. The
feeling passes as you find yourself before the gates of Hell, where
the spirits jeer at you and deny you entry.  Your senses are
disturbed.  The objects in the dungeon appear indistinct, bleached of
color, even unreal.
```

(I have patched the different known versions of the original Zork to run under Confusion. See https://github.com/heasm66/mdlzork)

**Comment by eriktorbjorn** [comment]
Someone must have _really_ liked this joke, by the way. Not only was it present in Zork, it is also in Enchanter (where it only responds to "PLAY KRILL" but doesn't work properly; see https://github.com/the-infocom-files/enchanter/issues/5), Infidel (only on objects with the ```VILLAIN``` bit, and I can't find any) and Cutthroats (where you can use it on other characters, but not yourself).

**Comment by AlexProudfoot** [comment]
Fixed.
