### ISSUE TITLE
Zork I [beta] - Probably unintentional TAB in tube description

### ISSUE THREAD

**Issue by eriktorbjorn** [the-infocom-files/zork1#6]
The code for the ```TUBE``` object looks like this:

```
<OBJECT TUBE
	(IN MAINTENANCE-ROOM)
	(SYNONYM TUBE TOOTH PASTE)
	(DESC "tube")
	(FLAGS TAKEBIT CONTBIT READBIT)
	(ACTION TUBE-FUNCTION)
	(LDESC
	 "There is an object which looks like a tube of toothpaste here.")
	(CAPACITY 7)
	(SIZE 5)
	(TEXT
"---> Frobozz Magic Gunk Company <---|
	  All-Purpose Gunk")>
```

So supposedly reading the tube should look like this, nice and centered:

```
>READ TUBE
---> Frobozz Magic Gunk Company <---
          All-Purpose Gunk
```

But since the first eight spaces of the second line is actually a TAB, the result is... unpredictable. In Frotz, it looks like:

```
>READ TUBE
---> Frobozz Magic Gunk Company <---
     All-Purpose Gunk
```

Then I tried it in various emulators (there are a few on the Internet Archive):

Apple II:

```
>READ TUBE
---> FROBOZZ MAGIC GUNK COMPANY <---
  ALL-PURPOSE-GUNK
```

Macintosh and Amiga:

```
>READ TUBE
---> Frobozz Magic Gunk Company <---
   All-Purpose Gunk
```

DOS

```
>READ TUBE
---> Frobozz Magic Gunk Company <---
o  All-Purpose Gunk
```

(Not actually an "o", but some sort of circle character.)

The development version of Zilf actually prints a warning about it:

```
[warning ZIL0410] /home/d91tan/src/Ancient/The Infocom Files/zork1/1dungeon.zil:1073: ZSCII 9 (tab) cannot be safely printed in Z-machine version 3
```

So it should probably be changed to eight spaces instead?

**Comment by AlexProudfoot** [comment]
Yes. Release 88 source code starts this line with <tab><space><space>. Replacing with ten spaces produces centred text.
